# Dockerfile.prod

# Stage 1: Build React app
FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Make sure both 80 and 443 are exposed
EXPOSE 80
EXPOSE 443

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
