version: '1.0'

services:

  front-app:
    build: ./front-app
    ports:
      - "3000:3000"
    volumes:
      - ./front-app:/app
    command: npm start

  back-app:
    build: ./back-app
    ports:
      - "5000:5000"
    volumes:
      - ./back-app:/app
    command: node ./index.js
